{{- if eq .Values.global.target "openshift" }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: dbgene
  name: gateway-service
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: "{{ .Values.global.imageRegistry }}/gateway-service:{{ .Values.global.version }}"
      importPolicy:
        insecure: true
        scheduled: true
      name: {{ .Values.global.version }}
      referencePolicy:
        type: Source
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: dbgene
  name: gateway-service
spec:
  replicas: 1
  selector:
    app: dbgene
    deploymentconfig: gateway-service
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: dbgene
        deploymentconfig: gateway-service
    spec:
      containers:
        - env:
            - name: JAVA_TOOL_OPTIONS
              value: -Xmx1024m
            - name: SERVICES_EXECUTION_HOST
              value: execution-service
            - name: SERVICES_EXECUTION_PORT
              value: '8080'
            - name: SERVICES_WEB_HOST
              value: web
            - name: SERVICES_WEB_PORT
              value: '8080'
            - name: SERVICES_BACKEND_HOST
              value: backend-service
            - name: SERVICES_BACKEND_PORT
              value: '8080'
            - name: SERVICES_GATEWAY_HOST
              value: gateway-service
            - name: SERVICES_GATEWAY_PORT
              value: '8080'
            - name: SERVICES_SCENARIO_HOST
              value: scenario-service
            - name: SERVICES_SCENARIO_PORT
              value: '8080'
            - name: SERVICES_DATA_HOST
              value: data-service
            - name: SERVICES_DATA_PORT
              value: '8080'
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: https://keycloak-{{ .Release.Namespace }}.{{ .Values.global.host }}/auth
          image: "{{ .Values.global.imageRegistry }}/gateway-service:{{ .Values.global.version }}"
          imagePullPolicy: Always
          name: gateway-service
          resources:
            limits:
              memory: {{ .Values.gatewayService.memLimit }}
            requests:
              cpu: {{ .Values.gatewayService.cpuRequest }}
              memory: {{ .Values.gatewayService.memRequest }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - gateway-service
        from:
          kind: ImageStreamTag
          name: gateway-service:{{ .Values.global.version }}
      type: ImageChange
    - type: ConfigChange
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: dbgene
  name: gateway
  annotations:
    haproxy.router.openshift.io/timeout: 10m
spec:
  host: {{ .Release.Namespace }}.{{ .Values.global.host }}
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: gateway-service
    weight: 100
  wildcardPolicy: None
# should be removed when okd API bug fixed (https://github.com/openshift/origin/issues/24060)
status:
  ingress:
    - conditions:
        - lastTransitionTime: "2019-12-06T03:24:58Z"
          status: "True"
          type: Admitted
      host: ""
      routerCanonicalHostname: ""
      routerName: default
      wildcardPolicy: None
{{- end }}
{{- if eq .Values.global.target "kubernetes" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dbgene
  name: gateway-service
spec:
  selector:
    matchLabels:
      app: dbgene
      deploymentconfig: gateway-service
  template:
    metadata:
      labels:
        app: dbgene
        deploymentconfig: gateway-service
    spec:
      containers:
        - env:
            - name: JAVA_TOOL_OPTIONS
              value: -Xmx1024m
            - name: SERVICES_EXECUTION_HOST
              value: execution-service
            - name: SERVICES_EXECUTION_PORT
              value: '8080'
            - name: SERVICES_WEB_HOST
              value: web
            - name: SERVICES_WEB_PORT
              value: '8080'
            - name: SERVICES_BACKEND_HOST
              value: backend-service
            - name: SERVICES_BACKEND_PORT
              value: '8080'
            - name: SERVICES_GATEWAY_HOST
              value: gateway-service
            - name: SERVICES_GATEWAY_PORT
              value: '8080'
            - name: SERVICES_SCENARIO_HOST
              value: scenario-service
            - name: SERVICES_SCENARIO_PORT
              value: '8080'
            - name: SERVICES_DATA_HOST
              value: data-service
            - name: SERVICES_DATA_PORT
              value: '8080'
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: https://keycloak-{{ .Release.Namespace }}.{{ .Values.global.host }}/auth
          image: "{{ .Values.global.imageRegistry }}/gateway-service:{{ .Values.global.version }}"
          imagePullPolicy: Always
          name: gateway-service
          resources:
            limits:
              memory: {{ .Values.gatewayService.memLimit }}
            requests:
              cpu: {{ .Values.gatewayService.cpuRequest }}
              memory: {{ .Values.gatewayService.memRequest }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: doc-web
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Release.Namespace }}.{{ .Values.global.host }}`) && PathPrefix(`/`)
      middlewares:
        - name: redirect
          namespace: kube-system
      services:
        - name: gateway-service
          port: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: doc-websecure
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Release.Namespace }}.{{ .Values.global.host }}`) && PathPrefix(`/`)
      services:
        - name: gateway-service
          port: 8080
  tls: {}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dbgene
  name: gateway-service
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: dbgene
    deploymentconfig: gateway-service
  sessionAffinity: None
  type: ClusterIP
